version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 19
  build:
    commands:
      - npm install
      - npm run build

artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - tsconfig.json
