version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo installed node version 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies..
      - node -e "console.log('Running Node.js ' + process.version)"
      - echo $(pwd)
      - echo $(ls)
  build:
    commands:
      - echo $(pwd)
      - echo $(ls)
      - npm install
      - npm run build
      - echo compiling using npm run build

artifacts:
  files:
    - '**/*'
